version: "3.8"

services:
  react-app:
    container_name: gabby
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # - /app/node_modules
    security_opt:
      - apparmor=unconfined
    stdin_open: true
    tty: true
